SELECT RES_CTO_ID, CTO_DESCRIPCION, sum(IF((RES_RESUL1-RES_RESUL2)>0, 1, 0)) AS GCASA,
sum(IF((RES_RESUL1-RES_RESUL2)=0, 1, 0)) AS ECASA,
sum(IF((RES_RESUL1-RES_RESUL2)<0, 1, 0)) AS PCASA
 FROM RESULTADOS, campeonatos
WHERE CTO_ID=RES_CTO_ID
group by RES_CTO_ID
order by CTO_DESCRIPCION